title: Cloudhost Status
languageCode: es
params:
  shortDateFormat: '15:04 — Jan 2'
  meta_description: >-
    Esta es la página de estado de Cloudhost, aquí encuentras el estado actual e
    histórico de incidentes.

    ¿No está de acuerdo con lo reportado aquí? escribanos a
    soporte@cloudhostla.com.ar.
  systems:
    - name: Website
      description: Our company public facing website
      link: 'https://www.example.com/'
    - name: Helpdesk
      description: Our company customer support site
      link: 'https://support.example.com/'
  dateFormat: 'January 2, 2006 at 15:04'
  disqusShortname: null
  timezoneString: ' UTC-3'
  logo: 'https://status.cloudhostla.com.ar/39e114dd-e384-460b-8a57-7100c367b942'
  description_header: >-
    Esta es la página de estado de <a class='text-grey-darkest' title='Visita
    Cloudhost' href='https://www.cloudhostla.com.ar/'>Cloudhost</a>.<br />aquí
    encuentras el estado actual e histórico de incidentes.<br/>

    ¿No está de acuerdo con lo reportado aquí? escribanos a
    soporte@cloudhostla.com.ar.
  copyrightHolder: Cloudhost by Nico Calvo
  eventsPerPage: 10
  iconType: image/png
  groups:
    - Servicios principales
  icon: /images/clearstatus.png
  description_footer: >-
    <a class='text-grey-darkest' title='Visit example.com'
    href='https://www.example.com/'>Example.com</a> provides open-source
    software for all kind of sectors.
