title: Cloudhost Status
languageCode: es
params:
  shortDateFormat: '15:04 — Jan 2'
  meta_description: >-
    Esta es la página de estado de Cloudhost, aquí encuentras el estado actual e
    histórico de incidentes.

    ¿No está de acuerdo con lo reportado aquí? escribanos a
    soporte@cloudhostla.com.ar.
  systems:
    - name: Website
      description: Our company public facing website
      link: 'https://www.example.com/'
    - name: Helpdesk
      description: Our company customer support site
      link: 'https://support.example.com/'
  dateFormat: 'January 2, 2006 at 3:04 PM'
  disqusShortname: null
  timezoneString: ' UTC-3'
  logo: >-
    https://cloudhostla.com.ar/wp-content/uploads/2020/03/cloudhost-logo-retina-blanco.png
  description_header: >-
    Information about <a class='text-grey-darkest' title='Visit example.com'
    href='https://www.example.com/'>example</a> systems operations.<br />Follow
    us <a class='text-grey-darkest' title='Visit our page on Twitter'
    href='https://www.twitter.com/example'>on Twitter</a> or subscribe to <a
    class='text-grey-darkest' href='%s' >RSS</a><br />to be alerted of new
    events.
  copyrightHolder: Example Inc.
  eventsPerPage: 10
  iconType: image/png
  groups:
    - Servicios principales
  icon: /images/clearstatus.png
  description_footer: >-
    <a class='text-grey-darkest' title='Visit example.com'
    href='https://www.example.com/'>Example.com</a> provides open-source
    software for all kind of sectors.
